name: build

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo $(which chromium-browser)

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "$GITHUB_SHA"

