name: build

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=NX_BASE::${{ github.event.pull_request.base.sha }}
      - run: echo "$NX_BASE"
      - run: echo "pull_request"
      - run: echo "$GITHUB_SHA"
      - uses: actions/cache@v1
        id: cache
        with:
          path: tmp
          key: cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: cache-${{ runner.os }}-
      - name: create
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir tmp
          echo ${{ github.sha }} > tmp/test.txt
      - name: output
        run: cat tmp/test.txt
