name: build

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=NX_BASE::${{ github.event.pull_request.base.sha }}
      - uses: actions/cache@v1
        with:
          path: tmp
          key: v1-${{ runner.os }}-tmp-${{ github.sha }}
          restore-keys: v1-${{ runner.os }}-tmp-
      - run: |
          if [ -d "tmp/" ]; then
            cat tmp/hoge.txt
          fi
      - run: |
          echo "$NX_BASE"
          echo "$GITHUB_SHA"
          mkdir -p tmp
          echo "$GITHUB_SHA" > tmp/hoge.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_SHA"

