name: build

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Chrome: $(which chrome)"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_SHA"

