name: build

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=NX_BASE::${{ github.event.pull_request.base.sha }}
      - run: echo "$NX_BASE"
      - run: echo "pull_request"
      - run: echo "$GITHUB_SHA"
      - run: echo ${{ github.run_id }}
      - run: echo ${{ github.run_number }}

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.run_id }}
      - run: echo ${{ github.run_number }}
