name: deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: tmptmp
          key: v1-${{ runner.os }}-tmptmp-${{ github.sha }}
          restore-keys: v1-${{ runner.os }}-tmptmp-
      - run: |
          if [ -d "tmptmp/" ]; then
            cat tmptmp/hoge.txt
          fi
      - run: |
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo "$GITHUB_SHA"
          mkdir -p tmptmp
          echo "$GITHUB_SHA" > tmptmp/hoge.txt
      - name: Set env
        run: |
          echo "NX_BASE=${{ github.event.before }}"
          echo BRANCH="${GITHUB_REF##*/}"
